In [1]:
#Importing Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')

In [2]:
#Loading and reading the dataset
log1 = pd.read_csv('China_Cross_Border_Ecommerce_Logistics_Dataset.csv')
log1

,shipment_id,order_id,transaction_date,platform_name,order_channel,origin_city_china,origin_province_china,warehouse_type,customs_port_china,destination_country,...,delivery_time_days,delivery_accuracy_pct,fulfillment_time_hr,logistics_cost_cny,fuel_cost_cny,carbon_emission_kg,return_request_flag,customer_rating,demand_variation_index,target_resource_allocation_status
0,CN-SHP-100000,CN-ORD-500000,2024-04-12,TikTok Shop Global,Wholesale Portal,Hangzhou,Zhejiang,Bonded Warehouse,Shanghai Customs,United Kingdom,...,13.73,91.97,361.35,732.39,291.14,58.66,No,4.6,0.368,Efficient_Allocation
1,CN-SHP-100001,CN-ORD-500001,2025-03-11,Temu,Wholesale Portal,Tianjin,Tianjin,Bonded Warehouse,Xiamen Customs,Indonesia,...,10.49,86.30,283.52,947.71,408.70,163.94,Yes,5.0,0.767,Balanced_Allocation
2,CN-SHP-100002,CN-ORD-500002,2024-09-27,Temu,Wholesale Portal,Ningbo,Zhejiang,Port-side Warehouse,Hangzhou Customs,Malaysia,...,26.13,92.22,643.98,494.09,128.52,49.44,Yes,4.1,0.581,Balanced_Allocation
3,CN-SHP-100003,CN-ORD-500003,2024-04-16,SHEIN Marketplace,Wholesale Portal,Shanghai,Shanghai,Bonded Warehouse,Zhengzhou Customs,United Arab Emirates,...,23.87,92.84,592.50,401.36,296.34,36.49,No,4.5,0.611,Balanced_Allocation
4,CN-SHP-100004,CN-ORD-500004,2024-03-12,Temu,Marketplace,Shanghai,Shanghai,Regional Fulfillment Center,Guangzhou Customs,Australia,...,6.02,88.82,190.41,861.86,230.27,97.64,No,4.1,0.538,Efficient_Allocation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,CN-SHP-106995,CN-ORD-506995,2025-12-12,JD Worldwide,Marketplace,Yiwu,Zhejiang,Regional Fulfillment Center,Hangzhou Customs,United States,...,11.31,93.38,300.87,526.83,1106.99,56.47,No,5.0,0.322,Efficient_Allocation
6996,CN-SHP-106996,CN-ORD-506996,2024-11-03,Made-in-China,Mobile App,Guangzhou,Guangdong,Smart Sorting Center,Qingdao Customs,France,...,28.70,94.57,715.97,540.15,910.87,87.64,Yes,2.6,0.411,Delayed_High_Cost
6997,CN-SHP-106997,CN-ORD-506997,2025-09-21,JD Worldwide,Marketplace,Guangzhou,Guangdong,Regional Fulfillment Center,Xiamen Customs,Japan,...,6.44,93.03,185.80,137.13,75.65,9.05,No,4.0,0.550,Efficient_Allocation
6998,CN-SHP-106998,CN-ORD-506998,2024-02-15,Made-in-China,Web Store,Guangzhou,Guangdong,Port-side Warehouse,Shenzhen Customs,United States,...,16.84,100.00,434.65,735.09,1055.99,41.43,No,4.3,0.561,Balanced_Allocation
6999,CN-SHP-106999,CN-ORD-506999,2024-10-28,SHEIN Marketplace,Marketplace,Ningbo,Zhejiang,Smart Sorting Center,Hangzhou Customs,South Korea,...,28.24,97.39,701.44,262.46,122.59,6.27,No,4.1,0.432,Balanced_Allocation

In [4]:
#Reading the first 5 rows of the data
log1.head()

,shipment_id,order_id,transaction_date,platform_name,order_channel,origin_city_china,origin_province_china,warehouse_type,customs_port_china,destination_country,...,delivery_time_days,delivery_accuracy_pct,fulfillment_time_hr,logistics_cost_cny,fuel_cost_cny,carbon_emission_kg,return_request_flag,customer_rating,demand_variation_index,target_resource_allocation_status
0,CN-SHP-100000,CN-ORD-500000,2024-04-12,TikTok Shop Global,Wholesale Portal,Hangzhou,Zhejiang,Bonded Warehouse,Shanghai Customs,United Kingdom,...,13.73,91.97,361.35,732.39,291.14,58.66,No,4.6,0.368,Efficient_Allocation
1,CN-SHP-100001,CN-ORD-500001,2025-03-11,Temu,Wholesale Portal,Tianjin,Tianjin,Bonded Warehouse,Xiamen Customs,Indonesia,...,10.49,86.30,283.52,947.71,408.70,163.94,Yes,5.0,0.767,Balanced_Allocation
2,CN-SHP-100002,CN-ORD-500002,2024-09-27,Temu,Wholesale Portal,Ningbo,Zhejiang,Port-side Warehouse,Hangzhou Customs,Malaysia,...,26.13,92.22,643.98,494.09,128.52,49.44,Yes,4.1,0.581,Balanced_Allocation
3,CN-SHP-100003,CN-ORD-500003,2024-04-16,SHEIN Marketplace,Wholesale Portal,Shanghai,Shanghai,Bonded Warehouse,Zhengzhou Customs,United Arab Emirates,...,23.87,92.84,592.50,401.36,296.34,36.49,No,4.5,0.611,Balanced_Allocation
4,CN-SHP-100004,CN-ORD-500004,2024-03-12,Temu,Marketplace,Shanghai,Shanghai,Regional Fulfillment Center,Guangzhou Customs,Australia,...,6.02,88.82,190.41,861.86,230.27,97.64,No,4.1,0.538,Efficient_Allocation

In [6]:
#Reading the last 5 rows of the data
log1.tail()

,shipment_id,order_id,transaction_date,platform_name,order_channel,origin_city_china,origin_province_china,warehouse_type,customs_port_china,destination_country,...,delivery_time_days,delivery_accuracy_pct,fulfillment_time_hr,logistics_cost_cny,fuel_cost_cny,carbon_emission_kg,return_request_flag,customer_rating,demand_variation_index,target_resource_allocation_status
6995,CN-SHP-106995,CN-ORD-506995,2025-12-12,JD Worldwide,Marketplace,Yiwu,Zhejiang,Regional Fulfillment Center,Hangzhou Customs,United States,...,11.31,93.38,300.87,526.83,1106.99,56.47,No,5.0,0.322,Efficient_Allocation
6996,CN-SHP-106996,CN-ORD-506996,2024-11-03,Made-in-China,Mobile App,Guangzhou,Guangdong,Smart Sorting Center,Qingdao Customs,France,...,28.70,94.57,715.97,540.15,910.87,87.64,Yes,2.6,0.411,Delayed_High_Cost
6997,CN-SHP-106997,CN-ORD-506997,2025-09-21,JD Worldwide,Marketplace,Guangzhou,Guangdong,Regional Fulfillment Center,Xiamen Customs,Japan,...,6.44,93.03,185.80,137.13,75.65,9.05,No,4.0,0.550,Efficient_Allocation
6998,CN-SHP-106998,CN-ORD-506998,2024-02-15,Made-in-China,Web Store,Guangzhou,Guangdong,Port-side Warehouse,Shenzhen Customs,United States,...,16.84,100.00,434.65,735.09,1055.99,41.43,No,4.3,0.561,Balanced_Allocation
6999,CN-SHP-106999,CN-ORD-506999,2024-10-28,SHEIN Marketplace,Marketplace,Ningbo,Zhejiang,Smart Sorting Center,Hangzhou Customs,South Korea,...,28.24,97.39,701.44,262.46,122.59,6.27,No,4.1,0.432,Balanced_Allocation

In [8]:
#Reading the statistics summary of the data for numerical variables
log1.describe().T

,count,mean,std,min,25%,50%,75%,max
item_quantity,7000.0,7.993571,4.313323,1.000,4.0000,8.000,12.0000,15.00
package_weight_kg,7000.0,3.894013,2.559543,0.200,2.0300,3.300,5.2400,19.61
package_volume_cbm,7000.0,0.059949,0.046575,0.001,0.0270,0.047,0.0790,0.38
order_value_cny,7000.0,1302.015931,729.693953,80.000,732.4250,1168.185,1755.0925,4699.46
declared_value_usd,7000.0,184.757723,103.608171,11.130,103.7475,166.405,249.0075,687.18
warehouse_inventory_level,7000.0,7515.717857,4329.864988,120.000,3706.0000,7470.000,11293.2500,14998.00
warehouse_capacity_utilization_pct,7000.0,71.651587,13.511979,35.000,62.4950,71.730,81.2450,98.00
inventory_availability_pct,7000.0,74.887440,9.215121,42.760,68.7400,74.815,81.2200,100.00
picking_time_min,7000.0,24.479103,7.852544,4.000,19.0600,24.510,29.9325,55.20
packing_time_min,7000.0,15.409490,5.005761,3.000,11.9875,15.410,18.7400,34.07
vehicle_capacity_kg,7000.0,2395.928571,2685.722756,500.000,800.0000,1200.000,2000.0000,10000.00
allocated_vehicle_load_kg,7000.0,1716.645001,2003.835146,225.110,508.9700,866.710,1817.1050,9786.03
resource_utilization_pct,7000.0,71.493456,15.342172,45.000,58.2200,71.190,84.8325,97.99
transport_distance_km,7000.0,7472.987987,3557.621838,900.000,4195.5975,8584.175,9834.4200,18046.99
scheduled_departure_delay_hr,7000.0,3.201096,3.229060,0.000,0.9200,2.250,4.3700,35.14
customs_document_completeness_pct,7000.0,90.371813,7.158999,61.040,85.3700,90.830,96.3500,100.00
customs_risk_score,7000.0,24.858616,11.368185,1.000,16.7300,24.545,32.4825,69.01
customs_clearance_time_hr,7000.0,19.133101,7.857299,2.000,13.5700,19.010,24.3525,49.26
cross_border_tax_cny,7000.0,123.500019,89.555787,3.960,56.3800,98.870,169.1425,668.97
tracking_update_count,7000.0,18.225143,9.167343,3.000,10.0000,18.000,26.0000,34.00
information_sharing_score,7000.0,83.076797,11.441258,41.190,75.4175,83.550,91.9325,100.00
partner_response_time_min,7000.0,44.129140,38.672208,2.000,17.0975,32.715,58.4475,357.27
data_sync_delay_min,7000.0,22.406487,18.530733,0.010,9.5875,17.010,29.5300,173.39
order_processing_time_hr,7000.0,3.160711,1.101230,0.500,2.4175,3.170,3.9000,7.10
delivery_time_days,7000.0,13.302099,7.772835,2.000,7.0200,9.850,20.4425,31.59
delivery_accuracy_pct,7000.0,92.578389,4.007858,77.540,89.8600,92.710,95.4600,100.00
fulfillment_time_hr,7000.0,344.745274,187.017522,52.670,193.6675,264.930,517.9550,794.02
logistics_cost_cny,7000.0,608.689701,264.876348,78.250,400.8325,576.195,786.5600,2218.79
fuel_cost_cny,7000.0,534.022821,346.559144,27.960,247.6500,469.235,774.9125,2075.93
carbon_emission_kg,7000.0,76.345906,76.557411,0.500,24.2575,51.285,103.1575,845.49
customer_rating,7000.0,4.315043,0.498841,2.100,4.0000,4.300,4.7000,5.00
demand_variation_index,7000.0,0.520064,0.176576,0.050,0.4020,0.519,0.6400,1.00

In [10]:
#Reading the statistcs summary of the categorical variables 
log1.describe(include = 'O').T

                                  count unique                   top  freq
shipment_id                        7000   7000         CN-SHP-100000     1
order_id                           7000   7000         CN-ORD-500000     1
transaction_date                   7000    730            2025-12-26    22
platform_name                      7000      8                  Temu   917
order_channel                      7000      5      Wholesale Portal  1435
origin_city_china                  7000     12               Chengdu   646
origin_province_china              7000      9              Zhejiang  1734
warehouse_type                     7000      5   Port-side Warehouse  1436
customs_port_china                 7000      9       Qingdao Customs   861
destination_country                7000     18         United States  1087
destination_region                 7000      7                Europe  2613
logistics_provider                 7000      9     YTO International   826
transport_mode                     7000      4           Air Freight  2907
product_category                   7000     10       Office Supplies   752
payment_method                     7000      6                PayPal  1243
customer_priority_level            7000      4                Medium  3169
return_request_flag                7000      2                    No  6168
target_resource_allocation_status  7000      5  Efficient_Allocation  3065

In [11]:
#Checking the length of the data
log1.shape

(7000, 50)

In [12]:
#Checking the summary of the data
log1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 50 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   shipment_id                         7000 non-null   object
 1   order_id                            7000 non-null   object
 2   transaction_date                    7000 non-null   object
 3   platform_name                       7000 non-null   object
 4   order_channel                       7000 non-null   object
 5   origin_city_china                   7000 non-null   object
 6   origin_province_china               7000 non-null   object
 7   warehouse_type                      7000 non-null   object
 8   customs_port_china                  7000 non-null   object
 9   destination_country                 7000 non-null   object
 10  destination_region                  7000 non-null   object
 11  logistics_provider                  7000 non-null   object
 12  transport_mode                      7000 non-null   object
 13  product_category                    7000 non-null   object
 14  payment_method                      7000 non-null   object
 15  customer_priority_level             7000 non-null   object
 16  item_quantity                       7000 non-null   int64
 17  package_weight_kg                   7000 non-null   float64
 18  package_volume_cbm                  7000 non-null   float64
 19  order_value_cny                     7000 non-null   float64
 20  declared_value_usd                  7000 non-null   float64
 21  warehouse_inventory_level           7000 non-null   int64
 22  warehouse_capacity_utilization_pct  7000 non-null   float64
 23  inventory_availability_pct          7000 non-null   float64
 24  picking_time_min                    7000 non-null   float64
 25  packing_time_min                    7000 non-null   float64
 26  vehicle_capacity_kg                 7000 non-null   int64
 27  allocated_vehicle_load_kg           7000 non-null   float64
 28  resource_utilization_pct            7000 non-null   float64
 29  transport_distance_km               7000 non-null   float64
 30  scheduled_departure_delay_hr        7000 non-null   float64
 31  customs_document_completeness_pct   7000 non-null   float64
 32  customs_risk_score                  7000 non-null   float64
 33  customs_clearance_time_hr           7000 non-null   float64
 34  cross_border_tax_cny                7000 non-null   float64
 35  tracking_update_count               7000 non-null   int64
 36  information_sharing_score           7000 non-null   float64
 37  partner_response_time_min           7000 non-null   float64
 38  data_sync_delay_min                 7000 non-null   float64
 39  order_processing_time_hr            7000 non-null   float64
 40  delivery_time_days                  7000 non-null   float64
 41  delivery_accuracy_pct               7000 non-null   float64
 42  fulfillment_time_hr                 7000 non-null   float64
 43  logistics_cost_cny                  7000 non-null   float64
 44  fuel_cost_cny                       7000 non-null   float64
 45  carbon_emission_kg                  7000 non-null   float64
 46  return_request_flag                 7000 non-null   object
 47  customer_rating                     7000 non-null   float64
 48  demand_variation_index              7000 non-null   float64
 49  target_resource_allocation_status   7000 non-null   object
dtypes: float64(28), int64(4), object(18)
memory usage: 2.7+ MB

# Data Preparation / Cleaning

In [13]:
#Saving a copy of the original dataset for future use
log = log1.copy(deep = True)
log

,shipment_id,order_id,transaction_date,platform_name,order_channel,origin_city_china,origin_province_china,warehouse_type,customs_port_china,destination_country,...,delivery_time_days,delivery_accuracy_pct,fulfillment_time_hr,logistics_cost_cny,fuel_cost_cny,carbon_emission_kg,return_request_flag,customer_rating,demand_variation_index,target_resource_allocation_status
0,CN-SHP-100000,CN-ORD-500000,2024-04-12,TikTok Shop Global,Wholesale Portal,Hangzhou,Zhejiang,Bonded Warehouse,Shanghai Customs,United Kingdom,...,13.73,91.97,361.35,732.39,291.14,58.66,No,4.6,0.368,Efficient_Allocation
1,CN-SHP-100001,CN-ORD-500001,2025-03-11,Temu,Wholesale Portal,Tianjin,Tianjin,Bonded Warehouse,Xiamen Customs,Indonesia,...,10.49,86.30,283.52,947.71,408.70,163.94,Yes,5.0,0.767,Balanced_Allocation
2,CN-SHP-100002,CN-ORD-500002,2024-09-27,Temu,Wholesale Portal,Ningbo,Zhejiang,Port-side Warehouse,Hangzhou Customs,Malaysia,...,26.13,92.22,643.98,494.09,128.52,49.44,Yes,4.1,0.581,Balanced_Allocation
3,CN-SHP-100003,CN-ORD-500003,2024-04-16,SHEIN Marketplace,Wholesale Portal,Shanghai,Shanghai,Bonded Warehouse,Zhengzhou Customs,United Arab Emirates,...,23.87,92.84,592.50,401.36,296.34,36.49,No,4.5,0.611,Balanced_Allocation
4,CN-SHP-100004,CN-ORD-500004,2024-03-12,Temu,Marketplace,Shanghai,Shanghai,Regional Fulfillment Center,Guangzhou Customs,Australia,...,6.02,88.82,190.41,861.86,230.27,97.64,No,4.1,0.538,Efficient_Allocation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,CN-SHP-106995,CN-ORD-506995,2025-12-12,JD Worldwide,Marketplace,Yiwu,Zhejiang,Regional Fulfillment Center,Hangzhou Customs,United States,...,11.31,93.38,300.87,526.83,1106.99,56.47,No,5.0,0.322,Efficient_Allocation
6996,CN-SHP-106996,CN-ORD-506996,2024-11-03,Made-in-China,Mobile App,Guangzhou,Guangdong,Smart Sorting Center,Qingdao Customs,France,...,28.70,94.57,715.97,540.15,910.87,87.64,Yes,2.6,0.411,Delayed_High_Cost
6997,CN-SHP-106997,CN-ORD-506997,2025-09-21,JD Worldwide,Marketplace,Guangzhou,Guangdong,Regional Fulfillment Center,Xiamen Customs,Japan,...,6.44,93.03,185.80,137.13,75.65,9.05,No,4.0,0.550,Efficient_Allocation
6998,CN-SHP-106998,CN-ORD-506998,2024-02-15,Made-in-China,Web Store,Guangzhou,Guangdong,Port-side Warehouse,Shenzhen Customs,United States,...,16.84,100.00,434.65,735.09,1055.99,41.43,No,4.3,0.561,Balanced_Allocation
6999,CN-SHP-106999,CN-ORD-506999,2024-10-28,SHEIN Marketplace,Marketplace,Ningbo,Zhejiang,Smart Sorting Center,Hangzhou Customs,South Korea,...,28.24,97.39,701.44,262.46,122.59,6.27,No,4.1,0.432,Balanced_Allocation

In [14]:
#Checking the summary of the copied dataset
log.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 50 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   shipment_id                         7000 non-null   object
 1   order_id                            7000 non-null   object
 2   transaction_date                    7000 non-null   object
 3   platform_name                       7000 non-null   object
 4   order_channel                       7000 non-null   object
 5   origin_city_china                   7000 non-null   object
 6   origin_province_china               7000 non-null   object
 7   warehouse_type                      7000 non-null   object
 8   customs_port_china                  7000 non-null   object
 9   destination_country                 7000 non-null   object
 10  destination_region                  7000 non-null   object
 11  logistics_provider                  7000 non-null   object
 12  transport_mode                      7000 non-null   object
 13  product_category                    7000 non-null   object
 14  payment_method                      7000 non-null   object
 15  customer_priority_level             7000 non-null   object
 16  item_quantity                       7000 non-null   int64
 17  package_weight_kg                   7000 non-null   float64
 18  package_volume_cbm                  7000 non-null   float64
 19  order_value_cny                     7000 non-null   float64
 20  declared_value_usd                  7000 non-null   float64
 21  warehouse_inventory_level           7000 non-null   int64
 22  warehouse_capacity_utilization_pct  7000 non-null   float64
 23  inventory_availability_pct          7000 non-null   float64
 24  picking_time_min                    7000 non-null   float64
 25  packing_time_min                    7000 non-null   float64
 26  vehicle_capacity_kg                 7000 non-null   int64
 27  allocated_vehicle_load_kg           7000 non-null   float64
 28  resource_utilization_pct            7000 non-null   float64
 29  transport_distance_km               7000 non-null   float64
 30  scheduled_departure_delay_hr        7000 non-null   float64
 31  customs_document_completeness_pct   7000 non-null   float64
 32  customs_risk_score                  7000 non-null   float64
 33  customs_clearance_time_hr           7000 non-null   float64
 34  cross_border_tax_cny                7000 non-null   float64
 35  tracking_update_count               7000 non-null   int64
 36  information_sharing_score           7000 non-null   float64
 37  partner_response_time_min           7000 non-null   float64
 38  data_sync_delay_min                 7000 non-null   float64
 39  order_processing_time_hr            7000 non-null   float64
 40  delivery_time_days                  7000 non-null   float64
 41  delivery_accuracy_pct               7000 non-null   float64
 42  fulfillment_time_hr                 7000 non-null   float64
 43  logistics_cost_cny                  7000 non-null   float64
 44  fuel_cost_cny                       7000 non-null   float64
 45  carbon_emission_kg                  7000 non-null   float64
 46  return_request_flag                 7000 non-null   object
 47  customer_rating                     7000 non-null   float64
 48  demand_variation_index              7000 non-null   float64
 49  target_resource_allocation_status   7000 non-null   object
dtypes: float64(28), int64(4), object(18)
memory usage: 2.7+ MB

In [15]:
#Checking the categorical variables in the dataset
log.select_dtypes('O').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 18 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   shipment_id                        7000 non-null   object
 1   order_id                           7000 non-null   object
 2   transaction_date                   7000 non-null   object
 3   platform_name                      7000 non-null   object
 4   order_channel                      7000 non-null   object
 5   origin_city_china                  7000 non-null   object
 6   origin_province_china              7000 non-null   object
 7   warehouse_type                     7000 non-null   object
 8   customs_port_china                 7000 non-null   object
 9   destination_country                7000 non-null   object
 10  destination_region                 7000 non-null   object
 11  logistics_provider                 7000 non-null   object
 12  transport_mode                     7000 non-null   object
 13  product_category                   7000 non-null   object
 14  payment_method                     7000 non-null   object
 15  customer_priority_level            7000 non-null   object
 16  return_request_flag                7000 non-null   object
 17  target_resource_allocation_status  7000 non-null   object
dtypes: object(18)
memory usage: 984.5+ KB

In [17]:
#checking the values in the variable platform_name
log.platform_name.value_counts()

platform_name
Temu                  917
Made-in-China         905
JD Worldwide          882
SHEIN Marketplace     876
DHgate                871
Alibaba Global        861
TikTok Shop Global    856
AliExpress            832
Name: count, dtype: int64

In [18]:
#Checking the values in the variable order_channel
log.order_channel.value_counts()

order_channel
Wholesale Portal    1435
Web Store           1417
Mobile App          1404
Social Commerce     1381
Marketplace         1363
Name: count, dtype: int64

In [19]:
#Checking the values in the variable origin_city_china
log.origin_city_china.value_counts()

origin_city_china
Chengdu      646
Suzhou       600
Shanghai     597
Qingdao      594
Ningbo       593
Yiwu         583
Xiamen       578
Shenzhen     569
Guangzhou    567
Hangzhou     558
Zhengzhou    558
Tianjin      557
Name: count, dtype: int64

In [20]:
#Checking the values in the variable origin_province_china
log.origin_province_china.value_counts()

origin_province_china
Zhejiang     1734
Guangdong    1136
Sichuan       646
Jiangsu       600
Shanghai      597
Shandong      594
Fujian        578
Henan         558
Tianjin       557
Name: count, dtype: int64

In [21]:
#Checking the values in the variable warehouse_type
log.warehouse_type.value_counts()

warehouse_type
Port-side Warehouse            1436
Bonded Warehouse               1428
Regional Fulfillment Center    1398
Export Warehouse               1394
Smart Sorting Center           1344
Name: count, dtype: int64

In [3]:
log1.isnull().sum()

shipment_id                           0
order_id                              0
transaction_date                      0
platform_name                         0
order_channel                         0
origin_city_china                     0
origin_province_china                 0
warehouse_type                        0
customs_port_china                    0
destination_country                   0
destination_region                    0
logistics_provider                    0
transport_mode                        0
product_category                      0
payment_method                        0
customer_priority_level               0
item_quantity                         0
package_weight_kg                     0
package_volume_cbm                    0
order_value_cny                       0
declared_value_usd                    0
warehouse_inventory_level             0
warehouse_capacity_utilization_pct    0
inventory_availability_pct            0
picking_time_min                      0
packing_time_min                      0
vehicle_capacity_kg                   0
allocated_vehicle_load_kg             0
resource_utilization_pct              0
transport_distance_km                 0
scheduled_departure_delay_hr          0
customs_document_completeness_pct     0
customs_risk_score                    0
customs_clearance_time_hr             0
cross_border_tax_cny                  0
tracking_update_count                 0
information_sharing_score             0
partner_response_time_min             0
data_sync_delay_min                   0
order_processing_time_hr              0
delivery_time_days                    0
delivery_accuracy_pct                 0
fulfillment_time_hr                   0
logistics_cost_cny                    0
fuel_cost_cny                         0
carbon_emission_kg                    0
return_request_flag                   0
customer_rating                       0
demand_variation_index                0
target_resource_allocation_status     0
dtype: int64